- name: Deploy catalogue binary
  unarchive:
    src: "{{ catalogue.bin }}"
    dest: /opt
    remote_src: yes
    mode: 0755
    
- name: copy supervisord script for catalogue
  template:
    src: catalogue.supervisor.conf.j2
    dest: /etc/supervisor/conf.d/catalogue.conf
    mode: 0755
  notify: restart supervisor

- meta: flush_handlers

- name: start catalogue service
  supervisorctl:
    name: catalogue
    state: started
